#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys
import os
import re
from send_speech import Stt

currentDir = os.path.dirname(os.path.realpath(__file__))
tries = 0
while True:
    if os.path.isfile(currentDir + '/Microphone/pycmd_nocmd'):
        os.system("rec -r 16000 -b 16 speech.flac silence 1 0.1 0.1% 1 1.0 0.1%")
        with open('speech.flac', 'r') as audio_file:
            content = audio_file.read()
        audio_file.closed

        stt = Stt()
        text = stt.speech_to_text(content)
        if text:
		question = text.encode('utf-8').strip().lower()
	        print 'Will pass the following to nodejs for analysis: ',question
		break
        else:
		if tries > 2:
			break
            	tries = tries + 1
		print 'No text was returned. Will try again.'
os.system("hotkeyagain")
